version: '3.8'

networks:
  default:

services:
  postgres:
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    # env_file: ./.env
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres:/var/lib/postgresql/data
    
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - default
    # volumes:
    #   - redis_data:/data

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis-stack
    networks:
      - default

volumes:
  postgres: